basePath: /api/v1
definitions:
  entities.GitlabMergeRequestHook:
    properties:
      assignees:
        items:
          properties:
            avatar_url:
              type: string
            id:
              type: integer
            name:
              type: string
            username:
              type: string
          type: object
        type: array
      changes:
        additionalProperties: true
        type: object
      event_type:
        type: string
      labels:
        items:
          type: string
        type: array
      object_attributes:
        properties:
          action:
            type: string
          assignee_id:
            type: integer
          assignee_ids:
            items:
              type: integer
            type: array
          author_id:
            type: integer
          blocking_discussions_resolved:
            type: boolean
          created_at:
            type: string
          description:
            type: string
          first_contribution:
            type: boolean
          id:
            type: integer
          iid:
            type: integer
          labels: {}
          last_commit:
            properties:
              author:
                properties:
                  email:
                    type: string
                  name:
                    type: string
                type: object
              id:
                type: string
              message:
                type: string
              timestamp:
                type: string
              url:
                type: string
            type: object
          merge_status:
            type: string
          milestone_id:
            type: string
          reviewer_ids:
            items:
              type: integer
            type: array
          source:
            additionalProperties: true
            type: object
          source_branch:
            type: string
          source_project_id:
            type: integer
          state:
            type: string
          target:
            properties:
              avatar_url:
                type: string
              default_branch:
                type: string
              description:
                type: string
              git_http_url:
                type: string
              git_ssh_url:
                type: string
              homepage:
                type: string
              http_url:
                type: string
              name:
                type: string
              namespace:
                type: string
              path_with_namespace:
                type: string
              ssh_url:
                type: string
              url:
                type: string
              visibility_level:
                type: integer
              web_url:
                type: string
            type: object
          target_branch:
            type: string
          target_project_id:
            type: integer
          title:
            type: string
          updated_at:
            type: string
          url:
            type: string
          work_in_progress:
            type: boolean
        type: object
      object_kind:
        type: string
      project:
        additionalProperties: true
        type: object
      repository:
        additionalProperties: true
        type: object
      reviewers:
        items:
          properties:
            avatar_url:
              type: string
            id:
              type: integer
            name:
              type: string
            username:
              type: string
          type: object
        type: array
      user:
        properties:
          avatar_url:
            type: string
          email:
            type: string
          id:
            type: integer
          name:
            type: string
          username:
            type: string
        type: object
    type: object
  entities.GitlabPushRequestHook:
    properties:
      after:
        type: string
      before:
        type: string
      checkout_sha:
        type: string
      commits:
        items:
          properties:
            added:
              items:
                type: string
              type: array
            author:
              properties:
                email:
                  type: string
                name:
                  type: string
              type: object
            id:
              type: string
            message:
              type: string
            modified:
              items:
                type: string
              type: array
            removed:
              items: {}
              type: array
            timestamp:
              type: string
            title:
              type: string
            url:
              type: string
          type: object
        type: array
      event_name:
        type: string
      object_kind:
        type: string
      project:
        properties:
          avatar_url: {}
          default_branch:
            type: string
          description:
            type: string
          git_http_url:
            type: string
          git_ssh_url:
            type: string
          homepage:
            type: string
          http_url:
            type: string
          id:
            type: integer
          name:
            type: string
          namespace:
            type: string
          path_with_namespace:
            type: string
          ssh_url:
            type: string
          url:
            type: string
          visibility_level:
            type: integer
          web_url:
            type: string
        type: object
      project_id:
        type: integer
      ref:
        type: string
      repository:
        properties:
          description:
            type: string
          git_http_url:
            type: string
          git_ssh_url:
            type: string
          homepage:
            type: string
          name:
            type: string
          url:
            type: string
          visibility_level:
            type: integer
        type: object
      total_commits_count:
        type: integer
      user_avatar:
        type: string
      user_email:
        type: string
      user_id:
        type: integer
      user_name:
        type: string
      user_username:
        type: string
    type: object
  gitlab.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  gitlab.SuccessResponse:
    properties:
      result:
        type: string
    type: object
host: localhost:80
info:
  contact:
    name: Fadeyev Artyom
    url: https://github.com/fadyat
  description: This is a sample server Hooks API.
  license:
    name: MIT
    url: https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE
  termsOfService: https://swagger.io/terms/
  title: Hooks API
  version: 1.0.0
paths:
  /api/v1/asana/merge:
    post:
      consumes:
      - application/json
      description: Endpoint to set last commit url to custom field in asana task,
        passed via commit message
      parameters:
      - description: Gitlab token
        in: header
        name: X-Gitlab-Token
        required: true
        type: string
      - description: Gitlab merge request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entities.GitlabMergeRequestHook'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gitlab.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gitlab.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gitlab.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gitlab.ErrorResponse'
      summary: Gitlab merge request hook
      tags:
      - gitlab
  /api/v1/asana/push:
    post:
      consumes:
      - application/json
      description: Endpoint to set last commit url to custom field in asana task,
        passed via commit message
      parameters:
      - description: Gitlab token
        in: header
        name: X-Gitlab-Token
        required: true
        type: string
      - description: Gitlab push request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entities.GitlabPushRequestHook'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gitlab.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gitlab.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gitlab.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gitlab.ErrorResponse'
      summary: Gitlab push request hook
      tags:
      - gitlab
  /api/v1/ping:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      tags:
      - example
schemes:
- http
- https
swagger: "2.0"
