name: analysis

on:
  pull_request:
    paths:
      - 'cmd/**'
      - 'api/**'
      - '.golangci.yml'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
    branches:
      - master

env:
  SWAGGO_VERSION: v1.16.2
  SWAGGER_PATH: api/docs/swagger.json
  GO_VERSION: '1.22.0'

jobs:
  run_linter:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: tests
        run: make tests
  verify_swagger:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install swaggo
        run: go install github.com/swaggo/swag/cmd/swag@${{ env.SWAGGO_VERSION }}
      - name: verify swagger
        run: |
          make swag
          git diff --exit-code -- ${{ env.SWAGGER_PATH }}
