name: analysis

on:
  push:
    paths:
      - 'cmd/**'
      - 'api/**'
      - '.golangci.yml'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
    branches:
      - master

env:
  SWAGGO_VERSION: v1.16.1
  SWAGGER_PATH: api/docs/swagger.json
  GO_VERSION: 1.19

jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: tests
        run: make tests
